/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BAB9.Interface;

/**
 *
 * @author Raditya Arya Wiguna
 */
public class GUI_BangunDatar extends javax.swing.JFrame {

    /**
     * Creates new form GUI_BangunDatar
     */
    public GUI_BangunDatar() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panjanglabel = new javax.swing.JLabel();
        lebar = new javax.swing.JLabel();
        cmbluas = new javax.swing.JComboBox<>();
        txtpertama = new javax.swing.JTextField();
        txtkedua = new javax.swing.JTextField();
        btnproses = new javax.swing.JButton();
        panjanglabel1 = new javax.swing.JLabel();
        lebar1 = new javax.swing.JLabel();
        sisia = new javax.swing.JTextField();
        sisib = new javax.swing.JTextField();
        lebar2 = new javax.swing.JLabel();
        sisic = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panjanglabel.setText("Panjang");

        lebar.setText("Lebar");

        cmbluas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persegi Panjang", "Segitiga sama kaki" }));
        cmbluas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbluasItemStateChanged(evt);
            }
        });
        cmbluas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbluasActionPerformed(evt);
            }
        });

        txtpertama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpertamaActionPerformed(evt);
            }
        });

        btnproses.setText("Hitung");
        btnproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesActionPerformed(evt);
            }
        });

        panjanglabel1.setText("Sisi A");

        lebar1.setText("Sisi B");

        sisia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisiaActionPerformed(evt);
            }
        });

        lebar2.setText("Sisi C");

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panjanglabel)
                        .addGap(18, 18, 18)
                        .addComponent(txtpertama))
                    .addComponent(cmbluas, 0, 356, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lebar1)
                        .addGap(32, 32, 32)
                        .addComponent(sisib))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lebar)
                            .addComponent(panjanglabel1))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtkedua)
                            .addComponent(sisia)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lebar2)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnproses, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sisic))))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbluas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(panjanglabel)
                            .addComponent(txtpertama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lebar)
                            .addComponent(txtkedua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(panjanglabel1)
                            .addComponent(sisia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lebar1)
                            .addComponent(sisib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lebar2)
                            .addComponent(sisic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnproses)
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbluasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbluasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbluasActionPerformed

    private void btnprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosesActionPerformed
        // TODO add your handling code here:
        if(cmbluas.getSelectedIndex()== 0){
            L1_PersegiPanjang P = new L1_PersegiPanjang();
            P.panjang = Integer.parseInt(txtpertama.getText());
            P.lebar = Integer.parseInt(txtkedua.getText());
            String hitung = "HASIL PERHITUNGAN\nKeliling : " + P.hitungKeliling() + "\n" +
                            "Luas : " + P.hitungluas();
            hasil.setText(hitung);
            }
        else if (cmbluas.getSelectedIndex()== 1) {
            L1_SegiTigaSamaKaki L = new L1_SegiTigaSamaKaki();
            L.alas = Double.parseDouble(txtpertama.getText());
            L.tinggi = Integer.parseInt(txtkedua.getText());
            L.a = Integer.parseInt(sisia.getText());
            L.b = Integer.parseInt(sisib.getText());
            L.c = Integer.parseInt(sisic.getText());
                
            String hitung = "HASIL PERHITUNGAN\nKeliling : " + L.hitungKeliling() + "\n" +
                            "Luas : " + L.hitungluas();
            hasil.setText(hitung);
        }

    }//GEN-LAST:event_btnprosesActionPerformed

    private void cmbluasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbluasItemStateChanged
        // TODO add your handling code here:
        if(cmbluas.getSelectedIndex() == 0) {
            panjanglabel.setText("Panjang");
            lebar.setText("Lebar");
            sisia.setEnabled(false);
            sisib.setEnabled(false);
            sisic.setEnabled(false);
        } else if (cmbluas.getSelectedIndex()== 1) {
            panjanglabel.setText("Alas");
            lebar.setText("Tinggi");
            sisia.setEnabled(true);
            sisib.setEnabled(true);
            sisic.setEnabled(true);
        }
    }//GEN-LAST:event_cmbluasItemStateChanged

    private void txtpertamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpertamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpertamaActionPerformed

    private void sisiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sisiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_BangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_BangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_BangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_BangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_BangunDatar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnproses;
    private javax.swing.JComboBox<String> cmbluas;
    private javax.swing.JTextArea hasil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lebar;
    private javax.swing.JLabel lebar1;
    private javax.swing.JLabel lebar2;
    private javax.swing.JLabel panjanglabel;
    private javax.swing.JLabel panjanglabel1;
    private javax.swing.JTextField sisia;
    private javax.swing.JTextField sisib;
    private javax.swing.JTextField sisic;
    private javax.swing.JTextField txtkedua;
    private javax.swing.JTextField txtpertama;
    // End of variables declaration//GEN-END:variables
}
